Moving to deb package

diff --git a/package/usr/bin/turntable2sonos b/package/usr/bin/turntable2sonos
--- a/package/usr/bin/turntable2sonos
+++ b/package/usr/bin/turntable2sonos
@@ -5,10 +5,9 @@ if [ ! -f /etc/turntable2sonos.cfg ]; then
     exit 1
 fi
 
-source /etc/turntable2sonos.cfg || { echo "Failed to source configuration file"; exit 1; }
+source /etc/turntable2sonos.cfg
 
 radio_url="http://$(hostname).local:8000/stream.mp3"
-
 echo "Sonos Device Name: $sonos_device_name"
 echo "ALSA Device: $alsa_device"
 echo "Debounce Interval: $debounce_interval_sec"
@@ -16,12 +15,32 @@ echo "Check Interval: $check_interval_sec"
 echo "Audio Threshold: $audio_threshold_db"
 echo "Radio URL: $radio_url"
 
-# Function to log messages to stdout
-log_message() {
-    echo "$(date '+%Y-%m-%d %H:%M:%S') : $1"
-}
+# Check if the ALSA device exists
+if ! aplay -L | grep -q "$alsa_device"; then
+    echo "ALSA device '$alsa_device' not found, exiting"
+    exit 1
+fi
 
-log_message "Starting audio listener script on ALSA device ${alsa_device}"
+/usr/bin/icecast2 -c /etc/turntable2sonos/icecast.xml &
+ICECAST_PID=$!
+if ! ps -p $ICECAST_PID > /dev/null; then
+    echo "Failed to start icecast2, exiting"
+    exit 1
+fi
+echo "Icecast server available at http://$(hostname).local:8000"
+
+/usr/bin/darkice -c /etc/turntable2sonos/darkice.cfg &
+DARKICE_PID=$!
+if ! ps -p $DARKICE_PID > /dev/null; then
+    echo "Failed to start darkice, exiting"
+    exit 1
+fi
+echo "Darkice started"
+
+# Kill the icecast2 and darkice services when the script is terminated
+trap "kill $DARKICE_PID $ICECAST_PID" EXIT
+
+echo "Startd audio listener script on ALSA device ${alsa_device}"
 
 # Initialize the last triggered time and silence start time
 last_triggered_timestamp=0
@@ -32,7 +51,7 @@ while true; do
 
     # Check if RMS amplitude was successfully retrieved
     if [[ -z "$rms_amplitude" ]]; then
-        log_message "Failed to retrieve RMS amplitude. Skipping this iteration."
+        echo "Failed to retrieve RMS amplitude. Skipping this iteration."
         sleep "$check_interval_sec"
         continue
     fi
@@ -41,7 +60,7 @@ while true; do
     exceeds_threshold=$(echo "$rms_amplitude > $audio_threshold_db" | bc -l)
 
     if [[ "$exceeds_threshold" != "1" && "$exceeds_threshold" != "0" ]]; then
-        log_message "Unexpected value for exceeds_threshold: '$exceeds_threshold'. Setting to 0."
+        echo "Unexpected value for exceeds_threshold: '$exceeds_threshold'. Setting to 0."
         exceeds_threshold=0
     fi
 
@@ -49,11 +68,11 @@ while true; do
 
     if [ "$exceeds_threshold" = "1" ]; then
         if [ $((current_time - last_triggered_timestamp)) -ge "$debounce_interval_sec" ]; then
-            log_message "Sound detected (RMS: $rms_amplitude), triggering Sonos to play radio"
+            echo "Sound detected (RMS: $rms_amplitude), triggering Sonos to play radio"
             sonos "$sonos_device_name" play_uri "$radio_url"
             last_triggered_timestamp=$current_time
         else
-            log_message "Sound detected but within debounce interval. Ignoring."
+            echo "Sound detected but within debounce interval. Ignoring."
         fi
     fi
 
